# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12b34a451e0dcbbbb0aceef3c9120a5eabe1c7ce7e8a4a5a065689c9b255ddce9289244861f94c8189d776c39361ab2337a32326940ad9c9832ca5252c659b12

test:
  secret_key_base: 2c1d2dfc35a7e8f1cea344ceffea4c1be1537e0ce5afc2472271daa4a4a1197925412a176cb4b7596f038389f3a0e89df161838ff19c17c8c097ad8651466e30

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
